# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # generic code formatting checkers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=4000']

  # python linter
  - repo: https://github.com/pycqa/flake8
    rev: '7.2.0'
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,E402

  # python code formatter
  - repo: https://github.com/psf/black
    rev: '25.1.0'
    hooks:
      - id: black
        # args:
        #   - --skip-string-normalization

  # jinja code formatter
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 'v1.36.4'
    hooks:
      - id: djlint-reformat
        args:
          - --profile=jinja

  # javascript linter
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.28.0'
    hooks:
      - id: eslint

  # css linter
  # (found to work better than csslint which was tried first)
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: 'v16.20.0'
    hooks:
      - id: stylelint
        args: [--fix]

  # javascript/css/markdown code formatter
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier
        language: node
        types_or: [javascript, css, markdown]

  # license header checker
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Add license header to Python files
        files: \.py$
        args:
          - --license-filepath
          - .pre-commit/license-header.txt
          - --comment-style
          - '#'
          - --use-current-year
      - id: insert-license
        name: Add license header to JavaScript files
        files: \.(js|jsx)$
        exclude: node_modules/
        args:
          - --license-filepath
          - .pre-commit/license-header.txt
          - --comment-style
          - '//'
          - --use-current-year
